### ISSUE TITLE
TemplateSyntaxError at / 

### ISSUE THREAD

**Issue by ghost** [svetlyak40wt/django-counter#1]
After having setted up everything I got this

 Caught an exception while rendering: ContentType matching query does not exist.
... 
DoesNotExist: ContentType matching query does not exist.

**Comment by svetlyak40wt** [comment]
Can you send a complete traceback, please?

**Comment by ghost** [comment]
seams to be solved
for some reason my ContentType class didn't load properly

**Comment by svetlyak40wt** [comment]
ok
